Documentation:
  Exclude:
    - lib/lita/handlers/puppet.rb

FileName:
  Exclude:
    - lib/lita-puppet.rb

Metrics/LineLength:
  Max: 100

Metrics/AbcSize:
  Max: 23

Metrics/MethodLength:
  Max: 25

Metrics/ClassLength:
  Max: 175

Metrics/BlockLength:
  Max: 30
  Exclude:
    - '*.gemspec'
    - Rakefile
    - 'spec/**/*_spec.rb'
    - 'spec/spec_helper.rb'
